name: 直播流媒体系统
dsn:
  # name: root:123456@(localhost:3306)/lsm?charset=utf8mb4&parseTime=True&loc=Local
  type: sqlite
  name: data/lsm.db3
http:
  port: 3080
  timeout: 15s
log:
  level: debug
svc:
  ipc:
    type: onv
    isc:
      addr: 
      appKey: 
      appSecret: 
      eventCallback: http://192.168.3.42/api/events
      eventType: 889196545
    ivs:
      addr: 
      appKey: 
      appSecret: 
      eventCallback: http://192.168.3.42/api/events
      eventType: 10310
    onv:
      userName: admin
      password: admin
