// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatemgt = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mgt/cameras": {
            "get": {
                "tags": [
                    "摄像头"
                ],
                "summary": "获取摄像头集合",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mdl.Camera"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "摄像头"
                ],
                "summary": "保存摄像头",
                "parameters": [
                    {
                        "description": "摄像头",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mdl.Camera"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/mgt/cameras/{code}/ptz/{command}/{speed}": {
            "post": {
                "tags": [
                    "摄像头"
                ],
                "summary": "控制云台",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头代码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命令: Left-左, Right-右, Up-上, Down-下, LeftUp-左上, LeftDown-左下, RightUp-右上, RightDown-右下, ZoomIn-放大, ZoomOut-缩小",
                        "name": "command",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 2,
                        "description": "速度: 1-慢, 2-中, 3-快",
                        "name": "speed",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/mgt/cameras/{code}/records/{date}": {
            "get": {
                "tags": [
                    "摄像头"
                ],
                "summary": "获取录像网址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头代码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mgt/cameras/{code}/streams/{type}/snapshot": {
            "post": {
                "tags": [
                    "摄像头"
                ],
                "summary": "抓取快照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头代码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 2,
                        "description": "类型: 1-主码流, 2-子码流",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mgt/cameras/{code}/streams/{type}/start": {
            "post": {
                "tags": [
                    "摄像头"
                ],
                "summary": "开始流",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头代码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 2,
                        "description": "类型: 1-主码流, 2-子码流",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mgt/cameras/{code}/streams/{type}/stop": {
            "post": {
                "tags": [
                    "摄像头"
                ],
                "summary": "停止流",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头代码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 2,
                        "description": "类型: 1-主码流, 2-子码流",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/mgt/cameras/{ids}": {
            "delete": {
                "tags": [
                    "摄像头"
                ],
                "summary": "移除摄像头集合",
                "parameters": [
                    {
                        "type": "string",
                        "description": "编码集合",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/mgt/cameras/{id}": {
            "get": {
                "tags": [
                    "摄像头"
                ],
                "summary": "获取摄像头",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mdl.Camera"
                        }
                    }
                }
            }
        },
        "/mgt/streams": {
            "get": {
                "tags": [
                    "流"
                ],
                "summary": "获取流集合",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mdl.Stream"
                            }
                        }
                    }
                }
            }
        },
        "/mgt/streams/start": {
            "post": {
                "tags": [
                    "流"
                ],
                "summary": "开始转推流",
                "parameters": [
                    {
                        "description": "流推送",
                        "name": "streamPush",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mdl.StreamPush"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/mgt/streams/stop": {
            "post": {
                "tags": [
                    "流"
                ],
                "summary": "停止转推流",
                "parameters": [
                    {
                        "description": "流推送",
                        "name": "streamPush",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mdl.StreamPush"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/mgt/streams/{id}": {
            "get": {
                "tags": [
                    "流"
                ],
                "summary": "获取流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mdl.Stream"
                        }
                    }
                }
            }
        },
        "/mgt/streams/{name}/push": {
            "get": {
                "tags": [
                    "流"
                ],
                "summary": "获取流推送",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mdl.Stream"
                        }
                    }
                }
            }
        },
        "/mgt/videos": {
            "get": {
                "tags": [
                    "视频"
                ],
                "summary": "获取视频集合",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mdl.Video"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "视频"
                ],
                "summary": "保存视频",
                "parameters": [
                    {
                        "description": "视频",
                        "name": "Video",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mdl.Video"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/mgt/videos/{ids}": {
            "delete": {
                "tags": [
                    "视频"
                ],
                "summary": "移除视频集合",
                "parameters": [
                    {
                        "type": "string",
                        "description": "编码集合",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/mgt/videos/{id}": {
            "get": {
                "tags": [
                    "视频"
                ],
                "summary": "获取视频",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mdl.Video"
                        }
                    }
                }
            }
        },
        "/mgt/videos/{id}/start": {
            "post": {
                "tags": [
                    "视频"
                ],
                "summary": "开始虚拟流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/mgt/videos/{id}/stop": {
            "post": {
                "tags": [
                    "视频"
                ],
                "summary": "停止虚拟流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/mgt/videowalls": {
            "get": {
                "tags": [
                    "视频墙"
                ],
                "summary": "获取视频墙集合",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "当前页",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mdl.VideoWall"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "视频墙"
                ],
                "summary": "保存视频墙",
                "parameters": [
                    {
                        "description": "视频墙",
                        "name": "videoWall",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mdl.VideoWall"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/mgt/videowalls/default": {
            "get": {
                "tags": [
                    "视频墙"
                ],
                "summary": "默认视频墙",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/mgt/videowalls/{ids}": {
            "delete": {
                "tags": [
                    "视频墙"
                ],
                "summary": "移除视频墙集合",
                "parameters": [
                    {
                        "type": "string",
                        "description": "编码集合",
                        "name": "ids",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/mgt/videowalls/{id}": {
            "get": {
                "tags": [
                    "视频墙"
                ],
                "summary": "获取视频墙",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mdl.VideoWall"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mdl.Camera": {
            "type": "object",
            "properties": {
                "addr": {
                    "description": "地址",
                    "type": "string"
                },
                "code": {
                    "description": "代码",
                    "type": "string"
                },
                "firmware": {
                    "description": "固件",
                    "type": "string"
                },
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "mfr": {
                    "description": "厂商",
                    "type": "string"
                },
                "model": {
                    "description": "型号",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "state": {
                    "description": "状态",
                    "type": "integer"
                },
                "type": {
                    "description": "类型",
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "mdl.Stream": {
            "type": "object",
            "properties": {
                "appName": {
                    "description": "应用名称",
                    "type": "string"
                },
                "audioCodec": {
                    "description": "音频解码",
                    "type": "string"
                },
                "codeRate": {
                    "description": "码率",
                    "type": "integer"
                },
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "protocol": {
                    "description": "协议",
                    "type": "string"
                },
                "pushs": {
                    "description": "推送集合",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mdl.StreamPush"
                    }
                },
                "receivedBytes": {
                    "description": "接收字节数",
                    "type": "integer"
                },
                "remoteAddr": {
                    "description": "远程地址",
                    "type": "string"
                },
                "sentBytes": {
                    "description": "发送字节数",
                    "type": "integer"
                },
                "session": {
                    "description": "会话",
                    "type": "string"
                },
                "subs": {
                    "description": "订阅集合",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mdl.StreamSub"
                    }
                },
                "type": {
                    "description": "类型",
                    "type": "string"
                },
                "videoCodec": {
                    "description": "视频解码",
                    "type": "string"
                },
                "videoHeight": {
                    "description": "视频高",
                    "type": "integer"
                },
                "videoWidth": {
                    "description": "视频宽",
                    "type": "integer"
                }
            }
        },
        "mdl.StreamPush": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "remoteAddr": {
                    "description": "远程地址",
                    "type": "string"
                },
                "state": {
                    "description": "状态",
                    "type": "integer"
                }
            }
        },
        "mdl.StreamSub": {
            "type": "object",
            "properties": {
                "codeRate": {
                    "description": "码率",
                    "type": "integer"
                },
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "protocol": {
                    "description": "协议",
                    "type": "string"
                },
                "receivedBytes": {
                    "description": "接收字节数",
                    "type": "integer"
                },
                "remoteAddr": {
                    "description": "远程地址",
                    "type": "string"
                },
                "sentBytes": {
                    "description": "发送字节数",
                    "type": "integer"
                },
                "session": {
                    "description": "会话",
                    "type": "string"
                },
                "type": {
                    "description": "类型",
                    "type": "string"
                }
            }
        },
        "mdl.Video": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "process": {
                    "description": "进程",
                    "type": "integer"
                },
                "source": {
                    "description": "来源",
                    "type": "string"
                },
                "url": {
                    "description": "网址",
                    "type": "string"
                }
            }
        },
        "mdl.VideoWall": {
            "type": "object",
            "properties": {
                "cameras": {
                    "description": "摄像头集合",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfomgt holds exported Swagger Info so clients can modify it
var SwaggerInfomgt = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "管理接口",
	Description:      "通用数据格式: {\"code\": \"200\", msg: \"\", data: object}, 其中 data 对应接口调用成功时数据格式.",
	InfoInstanceName: "mgt",
	SwaggerTemplate:  docTemplatemgt,
}

func init() {
	swag.Register(SwaggerInfomgt.InstanceName(), SwaggerInfomgt)
}
